Added starter
2desoo/HttpLoggingStarter pull request #1
Opened 2024-12-18 22:50 UTC by 2desoo

2024-12-19 07:33 UTC, Alexandr056 requested changes

2024-12-19 07:33 UTC, Alexandr056 commented on src/main/java/org/spring/dubrovsky/starter/HttpLoggingAspect.java
> +            logger.info("Method {} is about to execute", joinPoint.getSignature().getName());
а почему info?? условия Full, и вообще строка не настраиваемая

2024-12-19 07:33 UTC, Alexandr056 commented on src/main/java/org/spring/dubrovsky/starter/HttpLoggingAspect.java
> +            logger.info("Method {} executed successfully: {}", joinPoint.getSignature().getName(), result);
аналогично

2024-12-19 07:33 UTC, Alexandr056 commented on pom.xml
> +        <dependency>
тяжеловесно для стартера

2024-12-19 07:33 UTC, Alexandr056 commented on src/main/java/org/spring/dubrovsky/starter/HttpLoggingAspect.java
> +public class HttpLoggingAspect {
нет настройки уровня логирования

2024-12-21 16:41 UTC, 2desoo commented on src/main/java/org/spring/dubrovsky/starter/HttpLoggingAspect.java
> +            logger.info("Method {} is about to execute", joinPoint.getSignature().getName());
Исправил

2024-12-21 16:41 UTC, 2desoo commented on src/main/java/org/spring/dubrovsky/starter/HttpLoggingAspect.java
> +            logger.info("Method {} executed successfully: {}", joinPoint.getSignature().getName(), result);
Исправил

2024-12-21 16:43 UTC, 2desoo commented on pom.xml
> +        <dependency>
Исправил. Перепроверьте пожалуйста

2024-12-21 16:46 UTC, 2desoo commented on src/main/java/org/spring/dubrovsky/starter/HttpLoggingAspect.java
> +public class HttpLoggingAspect {
Исправил

2024-12-23 08:18 UTC, Alexandr056 approved these changes

2024-12-23 08:18 UTC, Alexandr056 commented on src/main/java/org/spring/dubrovsky/starter/HttpLoggingAspect.java
> +        if (properties.isEnabled()) {
эта проверка не нужна, для включения отключения логирования стоит создавать или не создавать бин, в вашем случае он есть, аспект срабатывает, и КАЖДЫЙ раз просто упирается в то что логировать не нужно

2024-12-23 08:18 UTC, Alexandr056 commented on src/main/java/org/spring/dubrovsky/starter/HttpLoggingAspect.java
> +    private void logWithLevel(HttpLoggingProperties.LogLevel logLevel, String message) {
сгодится)

2024-12-23 08:18 UTC, Alexandr056 commented on src/main/java/org/spring/dubrovsky/starter/HttpLoggingAspect.java
> +    private void logWithLevel(HttpLoggingProperties.LogLevel logLevel, String message) {
можно еще было установить для логгера уровень через setLevel а далее в лог писать logger.log()

2024-12-23 08:18 UTC, Alexandr056 commented on src/main/java/org/spring/dubrovsky/starter/HttpLoggingAutoConfiguration.java
> +@ConditionalOnProperty(prefix = "http.logging", name = "enabled", havingValue = "true", matchIfMissing = true)
свои настройки выносите в отдельную подгруппу, в рамках задания

2024-12-23 08:18 UTC, Alexandr056 commented on src/main/java/org/spring/dubrovsky/starter/HttpLoggingAutoConfiguration.java
> +@ConditionalOnProperty(prefix = "http.logging", name = "enabled", havingValue = "true", matchIfMissing = true)
кстати вот же верно! у вас бин не создатся если фла false, тогда зачем проверка в аспекте в его методах?

2024-12-25 22:20 UTC, merged